
module.exports = Object.freeze({
    MODAL_BODY_TYPES : {
        USER_DETAIL : "USER_DETAIL",
        LEAD_ADD_NEW : "LEAD_ADD_NEW",
        SEMESTRES_ADD_NEW:"SEMESTRES_ADD_NEW",
        SEMESTRES_UPDATE:"SEMESTRES_UPDATE",
        INTEGRANTE_ADD_NEW:"INTEGRANTE_ADD_NEW",
        DOCUMENTO_ADD_NEW:"DOCUMENTO_ADD_NEW",
        EMPRESAS_ADD_NEW : "EMPRESAS_ADD_NEW",
        EMPRESAS_UPDATE:"EMPRESAS_UPDATE",
        DOCUMENTACION_ADD_NEW:"DOCUMENTACION_ADD_NEW",
        FICHA_JURADO_ADD_NEW:"FICHA_JURADO_ADD_NEW",
        MODALIDAD_ADD_NEW : "MODALIDAD_ADD_NEW",
        MODALIDAD_UPDATE:"MODALIDAD_UPDATE",
        JURADOS_ADD_NEW:"JURADOS_ADD_NEW",
        PROYECTO_JURADO_ADD_NEW:"PROYECTO_JURADO_ADD_NEW",
        CONFIRMATION : "CONFIRMATION",
        DEFAULT : "",
    },

    RIGHT_DRAWER_TYPES : {
        NOTIFICATION : "NOTIFICATION",
        CALENDAR_EVENTS : "CALENDAR_EVENTS",
    },

    CONFIRMATION_MODAL_CLOSE_TYPES : {
        LEAD_DELETE : "LEAD_DELETE",
    },
});
